# creates a cacheMatrix object
# x should be a square matrix()
# set() can be used to set the matrix
# get() can be used to get the matrix
# setInverse() can be used to set the inverse
# getInverse() can be used to get the inverse (if calculated using cacheSolve())
makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setInverse <- function(inverse) m <<- inverse
  getInverse <- function() m
  list(set = set, get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}


# cacheSolve takes a cacheMatrix object (generated by makeCacheMatrix), and solves
# for its inverse.
# It will check if the inverse is already solved, and if so retrieve it, otherwise it will
# solve and cache the result.
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  m <- x$getInverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setInverse(m)
  m
}
